# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
#relative_permalinks: true

# Setup
title: Monero Node Deploy
tagline: Don\'t buy Monero.
description: Easy to use tool for deploying your own Monero node on AWS.
url: https://lzahq.tech
baseurl: /monero # no trailing slash

paginate: 1

# Cloudformation template version
version: 1.0

github:
  repo: https://github.com/poole/hyde

gems:
  - jekyll-paginate
