# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
#relative_permalinks: true

# Setup
title: Monero Node Deploy
tagline: ''
description: 'Easy to use tool for deploying your own Monero node on AWS.'
url:
baseurl: /

paginate: 1

# Cloudformation template version
version: 1.0

github:
  repo: https://github.com/poole/hyde

gems:
  - jekyll-paginate
