AWSTemplateFormatVersion: 2010-09-09
Description: RaiBlocks node deployment - github.com/lalanza808/raiblocks-node-deploy
Parameters:
  TargetVPC:
    Description: The VPC where resources will be launched.
    Type: 'AWS::EC2::VPC::Id'
  TargetVPCSubnet:
    Description: The public subnet where the node will reside.
    Type: 'AWS::EC2::Subnet::Id'
  InstanceType:
    Description: Web server instance type.
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m4.16xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.12xlarge
      - m5.24xlarge
    ConstraintDescription: Must be a valid EC2 instance type.
  KeyPairName:
    Description: SSH Key pair to be used by the web server instances.
    Type: 'AWS::EC2::KeyPair::KeyName'
  TrustedIPAddress:
    Description: Trusted IP address for managing the server - your IP returned from v4.icanhazip.com
    Type: String

Mappings:
  NodeAMI:
      us-east-1:
        "id": "ami-55ef662f"
      us-east-2:
        "id": "ami-15e9c770"
      us-west-1:
        "id": "ami-a51f27c5"
      us-west-2:
        "id": "ami-bf4193c7"
      ca-central-1:
        "id": "ami-d29e25b6"
      eu-west-2:
        "id": "ami-e7d6c983"

Resources:

  # Security Groups
  PublicNodeSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: raiblocks-public-node
      VpcId: !Ref TargetVPC
      GroupDescription: Enable inbound traffic for Raiblocks node specific communications.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 7075
          ToPort: 7075
          CidrIp: 0.0.0.0/0
        - IpProtocol: udp
          FromPort: 7075
          ToPort: 7075
          CidrIp: 0.0.0.0/0
  PrivateAccessSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: raiblocks-private-management
      VpcId: !Ref TargetVPC
      GroupDescription: Enable inbound management traffic to the instance.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub '${TrustedIPAddress}/32'

  # EC2
  NodeInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [NodeAMI, !Ref "AWS::Region", id]
      InstanceType: !Ref InstanceType
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 20
            VolumeType: gp2
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref PublicNodeSG
        - !Ref PrivateAccessSG
      SubnetId: !Ref TargetVPCSubnet
      Tags:
        - Key: Name
          Value: raiblocks-public-node
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -x
          echo -e "Hello world!"

  NodeEIP:
    Type: "AWS::EC2::EIP"
    Properties:
      InstanceId: !Ref NodeInstance
      Domain: vpc

Outputs:
  NodeIPAddress:
    Description: The IP address of your new RaiBlocks node
    Value: !Ref NodeEIP
